// ═══════════════════════════════════════════════════════════════
// js/logic/virtudes.js — Definição dos Virtoons do SESI
// ═══════════════════════════════════════════════════════════════

const VIRTUDES = [
  {
    id:        'compaixudo',
    nome:      'Compaixudo',
    virtude:   'Compaixão',
    descricao: 'Sente o que o outro sente e age para ajudar.',
    img:       'assets/virtudes/compaixudo.png',
    cor:       '#f0c040',
    corFundo:  'rgba(240,192,64,0.12)',
    emoji:     '🤗',
  },
  {
    id:        'generosina',
    nome:      'Generosina',
    virtude:   'Generosidade',
    descricao: 'Dá sem esperar nada em troca.',
    img:       'assets/virtudes/generosina.png',
    cor:       '#4a9aba',
    corFundo:  'rgba(74,154,186,0.12)',
    emoji:     '🎁',
  },
  {
    id:        'gentilene',
    nome:      'Gentilene',
    virtude:   'Gentileza',
    descricao: 'Trata todos com carinho e delicadeza.',
    img:       'assets/virtudes/gentilene.png',
    cor:       '#e06090',
    corFundo:  'rgba(224,96,144,0.12)',
    emoji:     '🌸',
  },
  {
    id:        'gratidoso',
    nome:      'Gratidoso',
    virtude:   'Gratidão',
    descricao: 'Reconhece e agradece o bem que recebe.',
    img:       'assets/virtudes/gratidoso.png',
    cor:       '#d4a017',
    corFundo:  'rgba(212,160,23,0.12)',
    emoji:     '🙏',
  },
  {
    id:        'honesticia',
    nome:      'Honestícia',
    virtude:   'Honestidade',
    descricao: 'Fala a verdade e age com integridade.',
    img:       'assets/virtudes/honesticia.png',
    cor:       '#3aaa7a',
    corFundo:  'rgba(58,170,122,0.12)',
    emoji:     '⚖️',
  },
  {
    id:        'humildoso',
    nome:      'Humildoso',
    virtude:   'Humildade',
    descricao: 'Reconhece seus limites e aprende com todos.',
    img:       'assets/virtudes/humildoso.png',
    cor:       '#7a88cc',
    corFundo:  'rgba(122,136,204,0.12)',
    emoji:     '🌱',
  },
  {
    id:        'justissauro',
    nome:      'Justissauro',
    virtude:   'Justiça',
    descricao: 'Defende o que é certo e trata todos com equidade.',
    img:       'assets/virtudes/justissauro.png',
    cor:       '#c05080',
    corFundo:  'rgba(192,80,128,0.12)',
    emoji:     '🦕',
  },
  {
    id:        'lealdina',
    nome:      'Lealdina',
    virtude:   'Lealdade',
    descricao: 'É fiel aos amigos e aos seus valores.',
    img:       'assets/virtudes/lealdina.png',
    cor:       '#38b0b0',
    corFundo:  'rgba(56,176,176,0.12)',
    emoji:     '🤝',
  },
  {
    id:        'paciencio',
    nome:      'Paciêncio',
    virtude:   'Paciência',
    descricao: 'Mantém a calma mesmo nas situações difíceis.',
    img:       'assets/virtudes/paciencio.png',
    cor:       '#9080c0',
    corFundo:  'rgba(144,128,192,0.12)',
    emoji:     '⏳',
  },
  {
    id:        'perseveroso',
    nome:      'Perseveroso',
    virtude:   'Perseverança',
    descricao: 'Não desiste diante dos obstáculos.',
    img:       'assets/virtudes/perseveroso.png',
    cor:       '#50a878',
    corFundo:  'rgba(80,168,120,0.12)',
    emoji:     '💪',
  },
  {
    id:        'respeitor',
    nome:      'Respeitor',
    virtude:   'Respeito',
    descricao: 'Valoriza e considera o espaço e as diferenças de todos.',
    img:       'assets/virtudes/respeitor.png',
    cor:       '#4898cc',
    corFundo:  'rgba(72,152,204,0.12)',
    emoji:     '🙌',
  },
  {
    id:        'segurido',
    nome:      'Segurido',
    virtude:   'Segurança',
    descricao: 'Transmite confiança e protege quem está ao redor.',
    img:       'assets/virtudes/segurido.png',
    cor:       '#8060b0',
    corFundo:  'rgba(128,96,176,0.12)',
    emoji:     '🛡️',
  },
  {
    id:        'solidari',
    nome:      'Solidari',
    virtude:   'Solidariedade',
    descricao: 'Une forças para ajudar quem precisa.',
    img:       'assets/virtudes/solidari.webp',
    cor:       '#d4a017',
    corFundo:  'rgba(212,160,23,0.12)',
    emoji:     '🤜',
  },
  {
    id:        'tolerany',
    nome:      'Tolerany',
    virtude:   'Tolerância',
    descricao: 'Aceita e respeita quem é diferente.',
    img:       'assets/virtudes/tolerany.webp',
    cor:       '#5aaccс',
    corFundo:  'rgba(90,172,204,0.12)',
    emoji:     '🌍',
  },
];

// Helpers
function getVirtude(id) {
  return VIRTUDES.find(v => v.id === id) || null;
}

function getVirtudePorNome(nome) {
  return VIRTUDES.find(v => v.nome === nome || v.id === nome) || null;
}
